server:
  port: 8081
spring:
#  Mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?
      ullNamePatternMatchesAll=true&amp;serverTimezone=GMT%2b8?
      useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  redis:
    port: 6379
    database: 0
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: root
#    listener:
#      direct:
#        retry:
#          enabled: true
#          max-attempts: 5
#          initial-interval: 5000
#          max-interval: 6000
#          multiplier: 20
#      simple:
#        default-requeue-rejected: true